### PR TITLE
Redesign of feedback tool frontend

### PR DESCRIPTION
**Pull request by svenpopping**

### CODE REVIEW

**Comment by svenpopping** [comment]
### Before
screenshot 2018-10-31 at 19 10 29

### After
screenshot 2018-10-31 at 19 10 33

**Comment by svenpopping** [comment]
### Before
screenshot 2018-10-31 at 19 54 32

### After
screenshot 2018-10-31 at 19 54 47

**Review by Fastjur — DISMISSED** [review]
This looks good to me. The login is currently broken though.

**Comment by svenpopping** [comment]
### Before

screenshot 2018-11-02 at 18 01 48


### After

screenshot 2018-11-02 at 18 09 29

**Comment by svenpopping** [comment]
@Fastjur could you review it?

**Review by Fastjur — APPROVED** [review]
This is looking amazing! Did you intentionally leave out a login/admin button on the frontpage like there used to be?

**Comment by Fastjur** [comment]
Also, I am missing the feature where you can click on a course and show all feedback that has been given to that course. That is something that is very useful. We should implement this too

**Comment by svenpopping** [comment]
> This is looking amazing! Did you intentionally leave out a login/admin button on the frontpage like there used to be?

I intentionally left it out, because regular users though they could login somehow. But the only login is for the admin part of the system.

**Comment by Fastjur** [comment]
@svenpopping I've added the overview of feedback per course. Do you want to review that?

**Comment by svenpopping** [comment]
LGTM

**Pull request merged**
