### PR TITLE
Fix edu feedback, course code now extracted from data sent by form

### PR DESCRIPTION
**Pull request by Fastjur**
Due to multiple people asking me today, I am merging this myself once the tests pass. As the feedback tool has apparently been down for quite some time now.

Signed-off-by: Jurriaan Den Toonder <jur.den.toonder@gmail.com>

### CODE REVIEW

**Review by svenpopping — CHANGES_REQUESTED** [review]
The problem is not in this part of the application, but somewhere in the autocomplete plugin

https://github.com/WISVCH/feedback-tool/blob/beb82b45c0d276ae37f538970da5a45b8204bd1d/src/main/resources/templates/education/educationForm.html#L54

So this isn't the solution to the problem

**Comment by Fastjur** [comment]
It is a solution. It even allows for both the input `TI1234 Test course` and `TI1234`.

**Comment by svenpopping** [comment]
Found the problem that causes this issue. The awesomplete dependency for some reason does not use the `value` anymore. Updating the dependency solves the problem, so I requested an version update at [webjars.org]().

**Comment by Fastjur** [comment]
So what is the status on this? The feedback tool is still not operational for education feedback.

**Pull request closed without merging**
